### ISSUE TITLE
An idea to make it quicker to delete spam

### ISSUE THREAD

**Issue by ScreapDK** [duckduckgo/community-platform#182]
The spam has been heavy lately. That and the fact that my laptop has a small screen has forced to scoll up and down tons of times to be able click the "Leave invisible" button, whenever there was a difference in the length of the content of the spam-post (and thus the height of `div` containing it).

I quickly checked out the CSS, and managed to add the following CSS code:
```CSS
.moderation .notification__comment {
   height: 350px;
   max-height: 350px;
   min-height: 350px;
   overflow-y: scroll;
}
```

This makes each `div` containing a spam message in the moderation-section always have an height of 350px. This means the "Leave invisible"-button is in the same place, every time a new spam message "moves up".

Would that be something you would consider adding?
Maybe you could make this option if most people don't want this?

I figured out that the changes should go into `notifications.css`, but I didn't add it as it should include the `.moderation`-part, and I don't know if you want *that* part to go in `notifications.css`.)
In case it can go there I can make a pull request! :) That would be my first one! xD ^_^

Let me know what you think! :)
